### ISSUE TITLE
Respawn: El personaje se vuelve inmune a la lava si cae sobre esta durante el periodo de invulnerabilidad post-spawn.

### ISSUE THREAD

**Issue by ferpg** [cusumdt/WhyMonstersWhy#5]
Si al respawnear un personaje cae sobre la lava antes que el periodo de invulnerabilidad se termine, este podrá caminar libremente sobre la lava hasta que otra acción o efecto del escenario lo mate.

Pasos de reproducción:

Paso 1: Morir en alguna de las plataformas más bajas.
Paso 2: Al respawnear, arrojarse rápidamente a la lava.

Resultado: Si el personaje aterriza sobre la lava antes de que se acabe el periodo de invulnerabilidad post-respawn, este podrá caminar libremente sobre la lava.

Referencia: https://drive.google.com/file/d/1OJU0dU1aQcQg1cZeuF4OCMujo9j_kCB5/view?usp=sharing

**Comment by undertaker725** [comment]
@ferpg el glich sigue sucediendo,re abrirlo
